FROM node:18-alpine

WORKDIR /app

# Установка зависимостей для разработки
COPY package*.json ./
COPY tsconfig*.json ./

RUN npm install

# Копирование исходного кода
COPY . .

# Открытие порта
EXPOSE 3000

# Запуск в режиме разработки
CMD ["npm", "run", "dev"]