FROM node:20-alpine

WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./
RUN npm ci

# Копируем исходный код
COPY . .

EXPOSE 5000

# Запускаем приложение (миграции выполняются в index.ts)
CMD ["npm", "run", "dev"]